### PR TITLE
Transform the feature in a behavior

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by rodfersou** [comment]
do ``plone.app.dexterity`` needs to be inserted as dependency into profile ``metadata.xml`` ?
it is not being installed on new instances.

**Comment by hvelarde** [comment]
you have to manually install `plone.app.contenttypes` in the control panel to test.

**Comment by hvelarde** [comment]
you have to manually install `plone.app.contenttypes` in the control panel to test.

**Comment by hvelarde** [comment]
a behavior is not supposed to install plone.app.contenttypes by default; that makes no sense: I can use a behavior in my own Dexterity content types without plone.app.contenttypes.

**Comment by rodfersou** [comment]
oh.. my mistake.. I didn't run buildoult here

**Pull request merged**
